### ISSUE TITLE
How to use read more

### ISSUE THREAD

**Issue by kenjisoul** [modernkernel/yii2-dotdotdot#3]
I want to change ... to read more and reload new url to read all text, How to do?

Thanks!

**Comment by harrytang** [comment]
Hi,

You can use 'clientOptions' to config the dotdotdot.

See http://dotdotdot.frebsite.nl/ for more info.

**Comment by kenjisoul** [comment]
Like this? but they not response this code. ??
`'clientOptions' => [
      '$(document).ready(function() {
            $(".ellipsis").dotdotdot({
                  after: "a.readmore"
            });
      });'
]`

**Comment by harrytang** [comment]
```
'clientOptions' => [
     'after'=>'a.readmore'
]
```

**Comment by kenjisoul** [comment]
Thank you.

**Comment by kenjisoul** [comment]
It's cannot use the script register like this 
`.dotdotdot({"after":"a.readmore"}); `

the register code is wrong, it's must be like this 
`dotdotdot({after: "a.readmore"	}); `

please fix it!
